### ISSUE TITLE
vue add vue-cli-plugin-pinia trows an error, and does not work afterwards (typescript dependency problem?)

### ISSUE THREAD

**Issue by Sjoerd82** [wobsoriano/vue-cli-plugin-pinia#1]
I executed:

`vue add vue-cli-plugin-pinia`

And got back:

```
📦  Installing vue-cli-plugin-pinia...


added 1 package, and audited 1682 packages in 3s

132 packages are looking for funding
  run `npm fund` for details

90 vulnerabilities (70 moderate, 18 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
✔  Successfully installed plugin: vue-cli-plugin-pinia


🚀  Invoking generator for vue-cli-plugin-pinia...
 ERROR  TypeError: Received an unexpected value [object Undefined]
TypeError: Received an unexpected value [object Undefined]
    at fromAST (C:\Users\Sjoerd\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\core.js:70:9)
    at core (C:\Users\Sjoerd\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\core.js:45:5)
    at newCore (C:\Users\Sjoerd\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\core.js:142:12)
    at toPropertyHash (C:\Users\Sjoerd\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\codemods\injectOptions.js:19:49)
    at Array.map (<anonymous>)
    at injectOptions (C:\Users\Sjoerd\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\codemods\injectOptions.js:20:42)
    at runTransformation (C:\Users\Sjoerd\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\vue-codemod\dist\src\runTransformation.js:60:17)
    at C:\Users\Sjoerd\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:290:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (C:\Users\Sjoerd\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:276:24)

```

Package.json now includes:

`"vue-cli-plugin-pinia": "~0.0.6",`

But no other reference to pinia (I was expecting a pinia dependency)

My main.ts:

```
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import vuetify from './plugins/vuetify'
import { createPinia, PiniaVuePlugin } from 'pinia'

import VueCompositionAPI from '@vue/composition-api'
Vue.use(VueCompositionAPI)

Vue.use(PiniaVuePlugin)
const pinia = createPinia()

Vue.config.productionTip = false

new Vue({
    router,
    pinia,
    vuetify,
    render: h => h(App),
}).$mount('#app')

```
But I receive an error:

```
Failed to compile.

./src/main.ts
Module not found: Error: Can't resolve 'pinia' in 'D:\Dev\NodeJs\project\src'

```
The reason I used the Vue CLI plugin is that I got a typescript dependency that was seemingly impossible to resolve.
So, it might be related to that. An npm install pinia returns:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: pinia@2.0.11
npm ERR! Found: typescript@4.1.6
npm ERR! node_modules/typescript
npm ERR!   peer typescript@">=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta" from tsutils@3.21.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin/node_modules/tsutils
npm ERR!     tsutils@"^3.7.0" from @typescript-eslint/eslint-plugin@1.13.0
npm ERR!     node_modules/@typescript-eslint/eslint-plugin
npm ERR!       @typescript-eslint/eslint-plugin@"^1.1.0" from @vue/eslint-config-typescript@4.0.0
npm ERR!       node_modules/@vue/eslint-config-typescript
npm ERR!         dev @vue/eslint-config-typescript@"^4.0.0" from the root project
npm ERR!   peer typescript@">=2" from @vue/cli-plugin-typescript@4.5.15
npm ERR!   node_modules/@vue/cli-plugin-typescript
npm ERR!     dev @vue/cli-plugin-typescript@"~4.5.0" from the root project
npm ERR!   4 more (ts-loader, tslint, tsutils, the root project)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@">=4.4.4" from pinia@2.0.11
npm ERR! node_modules/pinia
npm ERR!   pinia@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@4.5.5
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@">=4.4.4" from pinia@2.0.11
npm ERR!   node_modules/pinia
npm ERR!     pinia@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I'm on Vue2 (with the compostion API plugin)

**Comment by Sjoerd82** [comment]
Update: I've found a reference to this on the pinia github, and ran:

`npm install pinia --legacy-peer-deps`

This, I assume, ignores the typescript version. But I am still a bit confused about it all. What is the difference between a CLI-plugin and a 'direct install' like this anyway?
