### ISSUE TITLE
404 when try to swap vuex for pinia in presets

### ISSUE THREAD

**Issue by isimmons** [wobsoriano/vue-cli-plugin-pinia#3]
Not sure if this should work or if there is more to adding pinia as a preset.

.vuerc

```
{
  "useTaobaoRegistry": false,
  "presets": {
    "the-works": {
      "useConfigFiles": true,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-router": {
          "historyMode": false
        },
        "@vue/cli-plugin-vuex": {},
        "@vue/cli-plugin-eslint": {
          "config": "base",
          "lintOn": [
            "save"
          ]
        }
      },
      "vueVersion": "3"
    },
    "the-pinia-works": {
      "useConfigFiles": true,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-router": {
          "historyMode": false
        },
        "@vue/cli-plugin-pinia": {},
        "@vue/cli-plugin-eslint": {
          "config": "base",
          "lintOn": [
            "save"
          ]
        }
      },
      "vueVersion": "3"
    }
  }
}
```

Terminal ouput
```
Vue CLI v5.0.4
✨  Creating project in C:\Users\isimm\code\foobarbaz.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vue%2fcli-plugin-pinia - Not found
npm ERR! 404
npm ERR! 404  '@vue/cli-plugin-pinia@~5.0.0' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\isimm\AppData\Local\npm-cache\_logs\2022-06-07T11_11_58_572Z-debug-0.log
 ERROR  Error: command failed: npm install --loglevel error --legacy-peer-deps
Error: command failed: npm install --loglevel error --legacy-peer-deps
    at ChildProcess.<anonymous> (C:\Users\isimm\AppData\Roaming\nvm\v16.13.0\node_modules\@vue\cli\lib\util\executeCommand.js:138:16)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.cp.emit (C:\Users\isimm\AppData\Roaming\nvm\v16.13.0\node_modules\@vue\cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by isimmons** [comment]
I got rid of the '@vue/' in the name and it works. 

Sorry if this is expected behavior, I need to read up on plugin dev and what '@vue/' is for.

**Comment by wobsoriano** [comment]
Thanks for this!
